/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomNav: (typeof import('./src/components/BottomNav/index.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    SubmitButton: (typeof import('./src/components/SubmitButton/index.vue'))['default']
    VanCountDown: (typeof import('vant/es'))['CountDown']
    VanFloatingBubble: (typeof import('vant/es'))['FloatingBubble']
    VanNoticeBar: (typeof import('vant/es'))['NoticeBar']
    VanSwipe: (typeof import('vant/es'))['Swipe']
    VanSwipeItem: (typeof import('vant/es'))['SwipeItem']
    VanTabbar: (typeof import('vant/es'))['Tabbar']
    VanTabbarItem: (typeof import('vant/es'))['TabbarItem']
  }
}
